// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package oapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ProjectCreatedEventEvent.
const (
	ProjectCreated ProjectCreatedEventEvent = "project.created"
)

// Defines values for WebhookResponseStatus.
const (
	Error WebhookResponseStatus = "error"
	Ok    WebhookResponseStatus = "ok"
)

// ProjectCreatedEvent defines model for ProjectCreatedEvent.
type ProjectCreatedEvent struct {
	// Event The event type
	Event   ProjectCreatedEventEvent `json:"event"`
	Project ProjectDetails           `json:"project"`

	// Timestamp When the event occurred (UTC)
	Timestamp time.Time `json:"timestamp"`
}

// ProjectCreatedEventEvent The event type
type ProjectCreatedEventEvent string

// ProjectDetails defines model for ProjectDetails.
type ProjectDetails struct {
	// CreatedAt When the project was created (UTC)
	CreatedAt time.Time `json:"created_at"`

	// Id The project's unique identifier
	Id openapi_types.UUID `json:"id"`

	// Locale The project's locale (e.g., "en-US")
	Locale *string `json:"locale,omitempty"`

	// Name The project name
	Name string `json:"name"`

	// OrganizationId The organization the project belongs to
	OrganizationId openapi_types.UUID `json:"organization_id"`

	// Timezone The project's timezone (e.g., "America/New_York")
	Timezone *string `json:"timezone,omitempty"`
}

// WebhookResponse defines model for WebhookResponse.
type WebhookResponse struct {
	// Message Optional message, typically used for error details
	Message *string                `json:"message,omitempty"`
	Status  *WebhookResponseStatus `json:"status,omitempty"`
}

// WebhookResponseStatus defines model for WebhookResponse.Status.
type WebhookResponseStatus string

// ProjectCreatedWebhookJSONRequestBody defines body for ProjectCreatedWebhook for application/json ContentType.
type ProjectCreatedWebhookJSONRequestBody = ProjectCreatedEvent
